name: WinRAR Keygen
on: 
  workflow_dispatch:
    inputs:
      KEY_ENCODING:
        type: string
        description: License encoding ascii, ansi or utf8
        default: 'utf8'
        required: true

      KEY_USERNAME:
        type: string
        description: Input your username
        required: true
        
      KEY_LICENSE_NAME:
        type: string
        description: Input your license name
        default: 'Single PC usage license'
        required: true

jobs:
  keygen:
    name: Generating License (${{ github.event.inputs.KEY_ENCODING }})
    runs-on: windows-2022
    env:
      KEY_ENCODING: ${{ github.event.inputs.KEY_ENCODING }}
      KEY_USERNAME: ${{ github.event.inputs.KEY_USERNAME }}
      KEY_LICENSE_NAME: ${{ github.event.inputs.KEY_LICENSE_NAME }}

    steps:
    - uses: actions/checkout@v6.0.2
    
    - name: Generating License
      shell: pwsh
      run: |
        bin/x64-Release/winrar-keygen.exe "${{ env.KEY_USERNAME }}" "${{ env.KEY_LICENSE_NAME }}" -e ${{ env.KEY_ENCODING }}
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    - name: Uploading License
      uses: actions/upload-artifact@v6.0.0
      with:
        name: rarreg_file_${{ env.KEY_ENCODING }}
        path: rarreg.key
        if-no-files-found: error
        retention-days: 90
